### ISSUE TITLE
mpv 대체 프로그램 리서치

### ISSUE THREAD

**Issue by kybin** [kzmdstu/setup#7]
mpv가 속도는 빠르나 플레이 리스트를 직관적으로 확인, 수정할 수 없어 불편한 점이 있다.

Celluloid는 mpv의 gui를 수정한 클론이다. 설치해서 평가해 볼 것.

**Comment by kybin** [comment]
Celluloid 별로...

**Comment by kybin** [comment]
전에 테스트 해봤을 때는 약간 복잡했어요. 그리고 djv2가 동영상 재생도 괜찮은가요?

**Comment by kybin** [comment]
Clapper 테스트

`flatpak install flathub com.github.rafostar.Clapper`

**Comment by khw7096** [comment]
돈이 있다면.. pdplayer를 사서 사용하는 것도 방법이예요. rv는 shotgrid를 구매해야 쓸 수 있으니...

**Comment by kybin** [comment]
고마워요. 둘 다 한번 살펴볼게요!

**Comment by khw7096** [comment]
- OpenRV: https://github.com/AcademySoftwareFoundation/OpenRV
- XStudio: https://www.dneg.com/xstudio/
    - github: https://github.com/AcademySoftwareFoundation/xstudio

**Comment by kybin** [comment]
둘 다 빌드를 못해서 못쓰고 있었어요. 한웅씨는 빌드 성공했나요?
